config/routes.rb
Rails.application.routes.draw do
  resources :company_categories
  resources :admin_clients

  resources :order_transactions do
    collection do
      get :lost
    end
  end

  resources :product_ad_orders

  resources :orders do
    collection do
      get :update_pending, :approved, :pending, :cancelled
    end
    member do
      get 'approve'
      get 'cancel'
      get 'use_all'
      get 'dont_use_all'
      get 'use_coupon'
      get 'dont_use_coupon'
      get 'approve_coupon'
      get 'cancel_coupon'
    end
  end

  resources :product_ad_images

  resources :product_ads do
    member do
      get :duplicate
    end
  end

  resources :site_terms

  resources :pages

  resources :companies do
    collection do
      get :inactives
    end
  end

  resources :advertisements

  resources :cities

  resources :banners

  resources :holidays

  devise_for :clients, path: 'usuarios', path_names: { sign_in: 'entrar', sign_out: 'sair', registration: 'registro', sign_up: 'criar-conta', edit: 'meus-dados', password: 'senha' }
  devise_for :admins

  root 'pagina_inicial#index'

  get 'guia-empresarial' => 'guia_empresarial#index', as: :guia_empresarial
  get 'empresa/:id' => 'guia_empresarial#empresa', as: :empresa
  get 'area-atuacao/empresas/:id' => 'guia_empresarial#empresas_por_area_atuacao', as: :empresas_por_area_atuacao
  get 'ofertas/detalhes/:id' => 'ofertas#detalhes', as: :ofertas_detalhes
  get 'ofertas-disponiveis' => 'ofertas#disponiveis', as: :ofertas_disponiveis
  get 'ofertas-encerradas' => 'ofertas#encerradas', as: :ofertas_encerradas
  get 'minha-conta' => 'minha_conta#index', as: :minha_conta
  get 'minha-conta/validar-email' => 'minha_conta#validar_email', as: :validar_email
  get 'minha-conta/validar-cpf' => 'minha_conta#validar_cpf', as: :validar_cpf
  post 'minha-conta/notificacoes-compra' => 'minha_conta#notificacoes_compra', as: :notificacoes_compra, via: [:post]
  get 'regras-gerais' => 'paginas#regras_gerais', as: :regras_gerais
  get 'cupons' => 'minha_conta#cupons', as: :cupons
  get 'resultado-busca' => 'busca#index', as: :resultado_busca
  get 'cidades' => 'cidades#index', as: :cidades
  get 'trocar-cidade/:id' => 'cidades#trocar', as: :trocar_cidade
  get 'paginas/:link' => 'paginas#index', as: :pagina

  get 'carrinho' => 'carrinho#index', as: :carrinho
  get 'carrinho/adicionar/:id' => 'carrinho#adicionar', as: :carrinho_adicionar, via: [:get, :post]
  get 'carrinho/diminuir/:id' => 'carrinho#diminuir', as: :carrinho_diminuir
  get 'carrinho/remover/:id' => 'carrinho#remover', as: :carrinho_remover
  get 'carrinho/pagamento' => 'carrinho#pagamento', as: :carrinho_pagamento
  post 'carrinho/efetuar-pagamento' => 'carrinho#efetuar_pagamento', as: :carrinho_efetuar_pagamento
  get 'carrinho/processando' => 'carrinho#processando', as: :carrinho_processando

  get 'contato' => 'contato#index', as: :contato
  post 'contato/enviar' => 'contato#enviar', as: :contato_enviar_mensagem

  get 'painel-controle' => 'painel_controle#index', as: :painel_controle
  get 'painel-controle/administrar-oferta/:id' => 'painel_controle#administrar_oferta', as: :painel_controle_administrar_oferta
  get 'painel-controle/utilizar-cupon/:id' => 'painel_controle#utilizar_cupon', as: :painel_controle_utilizar_cupon
  get 'painel-controle/cupons-ativos' => 'painel_controle#cupons_ativos', as: :painel_controle_cupons_ativos
end

app/controllers/ofertas_controller.rb
class OfertasController < ApplicationController
  def detalhes
    @product_ad = ProductAd.where(active: true).friendly.find(params[:id])
    @product_ad.touch_views
  rescue
    redirect_to root_path
  end

  def disponiveis
    @product_ads = ProductAd.actives.only_masters.where(companies: {city_id: current_city_id}).order("product_ads.end_at, product_ads.start_at")
  end

  def encerradas
    @product_ads = ProductAd.expireds.where(companies: {city_id: current_city_id}).order("product_ads.end_at, product_ads.start_at")
  end
end

app/helpers/ofertas_helper.rb
module OfertasHelper
  def product_ad_interests(product_ad)
    count = product_ad.views.to_i + product_ad.product_ad_orders.count
    (content_tag(:span, count, class: "countdown-amount")+' Interesses por esta oferta').html_safe
  end

  def product_ad_images(product_ad)
    images = [ product_ad.image ] + product_ad.product_ad_images.map(&:image)
    images << product_ad.company.logo unless product_ad.company.logo_file_name.blank?
    images << product_ad.company.photo0 unless product_ad.company.photo0_file_name.blank?
    images
  end

  def product_ads_siblings(product_ad)
    @product_ads_siblings ||= begin
      if product_ad.product_ads.blank? && product_ad.product_ad.blank?
        nil
      else
        product_ads_siblings = []
        # is father
        unless product_ad.product_ads.blank?
          product_ads_siblings += product_ad.product_ads
        else
          product_ads_siblings << product_ad.product_ad
          product_ads_siblings += product_ad.product_ad.product_ads.where("id <> ?",product_ad.id)
        end
        product_ads_siblings.compact
      end
    end
  end
end

app/views/ofertas/detalhes.html.erb
<div class="breadcrumb">
  <div class="breadcrumb_inset">
    <a class="breadcrumb-home" href="/" title="Retornar a página inicial"><i class="icon-home"></i></a>
    <span class="navigation-pipe">»</span>
    <span class="navigation_page"><a href="<%= ofertas_disponiveis_path %>">Ofertas Disponíveis para <%= current_city.name %></a></span>
    <span class="navigation-pipe">»</span>
    <span class="navigation_page"><%= @product_ad.title %></span>
  </div>
</div>

<div id="primary_block" class="clearfix">
  <div class="row">
    <div id="pb-right-column" class="col-xs-12 col-sm-5">
      <h1 class="pb-right-colum-h"><%= @product_ad.title %></h1>
      <!-- product img-->
      <div id="image-block">
        <span id="view_full_size">
          <div id="wrap" style="top:0px;z-index:auto;position:relative;"><a id="zoom1" rel="position: 'inside' , showTitle: false, adjustX:0, adjustY:0" class="cloud-zoom" href="<%= @product_ad.image.url(:big) %>" style="position: relative; display: block;">
            <img id="mousetrap_img" alt="<%= @product_ad.title %>" width="106" height="106" title="<%= @product_ad.title %>" src="<%= @product_ad.image.url(:big) %>" rel="<%= @product_ad.image.url(:big) %>" style="display: block;">
            <img id="bigpic" alt="<%= @product_ad.title %>" title="<%= @product_ad.title %>" src="<%= @product_ad.image.url(:big) %>" rel="<%= @product_ad.image.url(:big) %>" style="display: block;"><span class="mask"></span>
          </a><div class="mousetrap" style="background-image:url(&quot;.&quot;);z-index:999;position:absolute;width:104px;height:104px;left:0px;top:0px;"></div></div>
        </span>
      </div>

      <!-- thumbnails -->
      <div id="views_block">
          <a id="view_scroll_left" title="Mais imagens" href="javascript:{}" style="cursor: default; opacity: 0; display: none;">Voltar</a>

          <div id="thumbs_list">
            <ul id="thumbs_list_frame" style="width: 712px;">
              <% product_ad_images(@product_ad).each_with_index do |image, i| %>
              <li id="thumbnail_<%= i %>">
                <a href="<%= image.url(:big) %>" class="cloud-zoom-gallery" title="" rel="useZoom: 'zoom1', smallImage: '<%= image.url(:big) %>'">
                  <img id="thumb_<%= i %>" src="<%= image.url(:thumb) %>" alt="">
                </a>
              </li>
              <% end %>
            </ul>
          </div>
        <a id="view_scroll_right" title="Mais imagens" href="javascript:{}" style="cursor: pointer; opacity: 1; display: block;">Avançar</a>
      </div>
      <div class="fb-like" data-href="<%= request.original_url %>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    </div>
    <!-- left infos-->
    <div id="pb-left-column" class="col-xs-12 col-sm-7">
      <h1><%= @product_ad.title %></h1>
      <div id="short_description_block">
        <div id="short_description_content" class="rte align_justify"><%= @product_ad.description.to_s.html_safe %></div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <h5 class="countdown text-center alert alert-warning" data-end-at="<%= @product_ad.end_at.to_s(:db) %>"></h5>
        </div>
        <div class="col-md-6">
          <h5 class="text-center alert alert-warning">
            <span class="countdown-section"><%= product_ad_interests(@product_ad) %></span>
          </h5>
        </div>
      </div>

      <!-- add to cart form-->
      <%= form_tag carrinho_adicionar_path(@product_ad), id: 'buy_block', method: :get do %>

        <div class="content_prices clearfix">
          <!-- prices -->

          <div class="row-2">
            <% if @product_ad.oferta? %>
            <p id="reduction_percent"><span id="reduction_percent_display" class="price label label-warning"><%= number_to_percentage(@product_ad.discount, precision: 2) %> de desconto</span></p>
            <p id="old_price">
              <span id="old_price_display"><%= number_to_currency(@product_ad.real_price) %></span>
            </p>
            <span class="on_sale">DISPONÍVEL!</span>
            <% else %>
            <span class="on_sale">DISPONÍVEL NO ESTABELECIMENTO!</span>
            <% end %>
          </div>

          <% if (@product_ad.minimum_per_client > 1) %>
          <div class="row-2">
            <span class="on_sale">Esta oferta exige uma quantidade mínima de <u><%= @product_ad.minimum_per_client %></u> unidades</p>
          </div>
          <% end %>

          <div class="row_1">
            <p class="our_price_display">
              <% if @product_ad.oferta? %>
              <span id="our_price_display"><%= number_to_currency(@product_ad.special_price) %> <small>por cupom</small></span>
              <% else %>
              <span id="our_price_display">Vale Cupom</span>
              <% end %>
              <!---->
            </p>
            <% if @product_ad.can_be_sold? %>
            <p id="add_to_cart" class="buttons_bottom_block">
              <a class="exclusive button btn btn-default btn_add_cart" href="javascript:;"> <span>Quero esta oferta!</span></a>
            </p>
            <!-- quantity wanted -->
            <p id="quantity_wanted_p">
              <label>Quantidade:</label>
              <a href="javascript:;" class="product_quantity_down button btn btn-default" rel="qty"><i class="icon-minus"></i></a>
              <input type="text" name="qty" id="quantity_wanted" class="form-control" value="1" size="2" maxlength="3">
              <a href="javascript:;" class="product_quantity_up button btn btn-default" quantity-available="<%= @product_ad.maximum_per_client %>" rel="qty"><i class="icon-plus"></i></a>
            </p>
            <% end -%>
          </div>
        </div>

      <% end %>

      <p id="loyalty">
        <i class="icon-info-sign"></i>
        <em>
          Adquirindo esta oferta você estará <strong>aceitando automaticamente os termos</strong> citados abaixo e as <strong><a href="/regras-gerais">regras gerais de ofertas</a></strong> propostas no seu cadastro.
        </em>
      </p>

      <% unless product_ads_siblings(@product_ad).blank? %>
        <div class="main_page_products block">
          <h4><span>Outras opções para esta oferta</span></h4>
          <% product_ads_siblings(@product_ad).in_groups_of(2,false).each do |grouped| %>
          <ul class="row">
            <% grouped.each do |product_ad| %>
            <li class="ajax_block_product col-xs-6 col-sm-6 col-md-6 first_item_of_line first_item_of_tablet_line">
              <div class="inner_content clearfix">
                <% unless defined?(show_city) %>
                  <% if product_ad.newer? %>
                  <div class="sale-box"><span class="before"></span><span class="after"></span><span class="on_sale title_shop">Novidade!</span></div>
                  <% end %>

                  <% if product_ad.ending? %>
                  <div class="new-box"><span class="before"></span><span class="after"></span><span class="new">Encerrando!</span></div>
                  <% end %>


                <% else %>
                  <div class="sale-box"><span class="before"></span><span class="after"></span><span class="on_sale title_shop"><%= truncate(product_ad.city.name) %></span></div>
                <% end -%>
                <div class="product_image"><a href="<%= ofertas_detalhes_path(product_ad) %>" title="<%= time_ago_in_words(product_ad.end_at) %> para finalizar" class="product_image"><img src="<%= product_ad.image.url(:box) %>" alt="<%= time_ago_in_words(product_ad.end_at) %> para finalizar" /></a></div>
                <div class="product_content">
                  <div class="inner_content1">
                    <h5><a class="product_link" href="<%= ofertas_detalhes_path(product_ad) %>" title="<%= number_to_percentage(product_ad.discount, precision: 2) %> de desconto"><%= product_ad.title %></a></h5>
                    <p class="price_container"><span class="price"><%= product_ad_price(product_ad) %></span></p>
                  </div>
                  <a class="button btn btn-default view" href="<%= ofertas_detalhes_path(product_ad) %>" title="Ver Oferta"><i class="icon-info-sign"></i></a>
                  <% if product_ad.can_be_sold? %>
                  <a class="exclusive btn btn-default ajax_add_to_cart_button btn_add_cart" href="<%=carrinho_adicionar_path(product_ad) %>" title="Adicionar Oferta"><span></span></a>
                  <% end -%>
                </div>
              </div>
            </li>
            <% end %>
          </ul>
          <% end -%>
        </div>
      <% end -%>
    </div>
  </div>

</div>
<div class="clear"></div>
<section class="page_product_box toggle_frame more_info_inner" style="margin-top: 20px">
  <h3 class="toggle">Termos declarados pelo anunciante<i class="icon-toggle icon-minus-sign-alt"></i></h3>
  <div class="toggle_content">
    <%= @product_ad.terms.to_s.html_safe %>
  </div>
</section>
<div class="clear"></div>
<section class="page_product_box toggle_frame more_info_inner" style="margin-bottom: 20px">
  <h3 class="toggle">Informações do anunciante<i class="icon-toggle icon-minus-sign-alt"></i></h3>
  <div class="toggle_content">
    <div class="row">
      <div class="col-md-3"><img src="<%= @product_ad.company.logo.url %>" /></div>
      <div class="col-md-9">
        <table class="table table-bordered">
          <tr>
            <td class="active col-md-3">Anunciante</td>
            <td class="notice"><strong><%= @product_ad.company.name %></strong></td>
          </tr>
          <tr>
            <td class="active col-md-3">Endereço</td>
            <td class="notice"><strong><%= @product_ad.company.address %></strong></td>
          </tr>
          <% unless @product_ad.company.site.blank? %>
          <tr>
            <td class="active col-md-3">Site</td>
            <td class="notice"><strong><%= @product_ad.company.site %></strong></td>
          </tr>
          <% end -%>
          <tr>
            <td class="active col-md-3">Responsável</td>
            <td class="notice"><strong><%= @product_ad.company.contact_name %></strong></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</section>

<% if @product_ad.company.product_ads.actives.only_masters.count > 0 %>
<div class="clear"></div>
<div class="block main_page_products">
  <h4><span>Outras ofertas de <u><%= @product_ad.company.name %></u></span></h4>
  <%= render partial: 'shared/product_ad_box', locals: {product_ads: @product_ad.company.product_ads.actives.only_masters} %>
</div>
<% end -%>
<div class="clear"></div>

<div class="fb-comments" data-href="<%= request.original_url %>" data-width="100%" data-numposts="3" data-colorscheme="light"></div>

app/views/ofertas/disponiveis.html.erb
<div id="featured-products_block_center" class="main_page_products block">
  <h4><span><u><%= @product_ads.count %></u> ofertas disponíveis para <u><%= current_city.name %></u></span></h4>
  <%= render partial: 'shared/product_ad_box', locals: {product_ads: @product_ads} %>
</div>

app/views/ofertas/encerradas.html.erb
<div id="featured-products_block_center" class="main_page_products block">
  <h4><span><u><%= @product_ads.count %></u> ofertas encerradas para <u><%= current_city.name %></u></span></h4>
  <%= render partial: 'shared/product_ad_box', locals: {product_ads: @product_ads} %>
</div>