config/routes.rb
Rails.application.routes.draw do
  resources :company_categories
  resources :admin_clients

  resources :order_transactions do
    collection do
      get :lost
    end
  end

  resources :product_ad_orders

  resources :orders do
    collection do
      get :update_pending, :approved, :pending, :cancelled
    end
    member do
      get 'approve'
      get 'cancel'
      get 'use_all'
      get 'dont_use_all'
      get 'use_coupon'
      get 'dont_use_coupon'
      get 'approve_coupon'
      get 'cancel_coupon'
    end
  end

  resources :product_ad_images

  resources :product_ads do
    member do
      get :duplicate
    end
  end

  resources :site_terms

  resources :pages

  resources :companies do
    collection do
      get :inactives
    end
  end

  resources :advertisements

  resources :cities

  resources :banners

  resources :holidays

  devise_for :clients, path: 'usuarios', path_names: { sign_in: 'entrar', sign_out: 'sair', registration: 'registro', sign_up: 'criar-conta', edit: 'meus-dados', password: 'senha' }
  devise_for :admins

  root 'pagina_inicial#index'

  get 'guia-empresarial' => 'guia_empresarial#index', as: :guia_empresarial
  get 'empresa/:id' => 'guia_empresarial#empresa', as: :empresa
  get 'area-atuacao/empresas/:id' => 'guia_empresarial#empresas_por_area_atuacao', as: :empresas_por_area_atuacao
  get 'ofertas/detalhes/:id' => 'ofertas#detalhes', as: :ofertas_detalhes
  get 'ofertas-disponiveis' => 'ofertas#disponiveis', as: :ofertas_disponiveis
  get 'ofertas-encerradas' => 'ofertas#encerradas', as: :ofertas_encerradas
  get 'minha-conta' => 'minha_conta#index', as: :minha_conta
  get 'minha-conta/validar-email' => 'minha_conta#validar_email', as: :validar_email
  get 'minha-conta/validar-cpf' => 'minha_conta#validar_cpf', as: :validar_cpf
  post 'minha-conta/notificacoes-compra' => 'minha_conta#notificacoes_compra', as: :notificacoes_compra, via: [:post]
  get 'regras-gerais' => 'paginas#regras_gerais', as: :regras_gerais
  get 'cupons' => 'minha_conta#cupons', as: :cupons
  get 'resultado-busca' => 'busca#index', as: :resultado_busca
  get 'cidades' => 'cidades#index', as: :cidades
  get 'trocar-cidade/:id' => 'cidades#trocar', as: :trocar_cidade
  get 'paginas/:link' => 'paginas#index', as: :pagina

  get 'carrinho' => 'carrinho#index', as: :carrinho
  get 'carrinho/adicionar/:id' => 'carrinho#adicionar', as: :carrinho_adicionar, via: [:get, :post]
  get 'carrinho/diminuir/:id' => 'carrinho#diminuir', as: :carrinho_diminuir
  get 'carrinho/remover/:id' => 'carrinho#remover', as: :carrinho_remover
  get 'carrinho/pagamento' => 'carrinho#pagamento', as: :carrinho_pagamento
  post 'carrinho/efetuar-pagamento' => 'carrinho#efetuar_pagamento', as: :carrinho_efetuar_pagamento
  get 'carrinho/processando' => 'carrinho#processando', as: :carrinho_processando

  get 'contato' => 'contato#index', as: :contato
  post 'contato/enviar' => 'contato#enviar', as: :contato_enviar_mensagem

  get 'painel-controle' => 'painel_controle#index', as: :painel_controle
  get 'painel-controle/administrar-oferta/:id' => 'painel_controle#administrar_oferta', as: :painel_controle_administrar_oferta
  get 'painel-controle/utilizar-cupon/:id' => 'painel_controle#utilizar_cupon', as: :painel_controle_utilizar_cupon
  get 'painel-controle/cupons-ativos' => 'painel_controle#cupons_ativos', as: :painel_controle_cupons_ativos
end

app/controllers/painel_controle_controller.rb
class PainelControleController < ApplicationController
  before_action :redirect_unless_company

  def index
    @active_product_ads = ProductAd.actives.where(company_id: current_client.company_id).all.sort{|t| t.total_coupons}.reverse
    @expired_product_ads = ProductAd.expireds.where(company_id: current_client.company_id).order(:end_use_at, :start_use_at)
  end

  def administrar_oferta
    @product_ad = ProductAd.friendly.find(params[:id])
  end

  def utilizar_cupon
    @product_ad_order = current_client.company.product_ad_orders.where(coupon: params[:id]).first
    if @product_ad_order.use_coupon
      flash[:success] = 'Cupom marcado como utilizado com sucesso'
    end
    redirect_to :back
  end

  def redirect_unless_company
    unless company_signed_in?
      flash[:error] = 'Você não tem acesso a esta área. Entre em contato conosco para se tornar um anunciante.'
      redirect_to contato_path
    end
  end
end

app/helpers/painel_controle_helper.rb
module PainelControleHelper
  def product_ad_total_coupons(product_ad)

  end
end

app/views/painel_controle/_product_ad_box.erb
<% product_ads.in_groups_of(4,false).each do |grouped| %>
<ul class="row">
  <% grouped.each do |product_ad| %>
  <li class="ajax_block_product col-xs-6 col-sm-6 col-md-3 first_item_of_line first_item_of_tablet_line">
    <div class="inner_content clearfix">
      <% unless product_ad.expired? %>
        <% if product_ad.newer?(:company) %>
        <div class="sale-box"><span class="before"></span><span class="after"></span><span class="on_sale title_shop">Novidade!</span></div>
        <% end %>

        <% if product_ad.ending?(:company) %>
        <div class="new-box"><span class="before"></span><span class="after"></span><span class="new">Encerrando!</span></div>
        <% end %>
      <% else %>
        <div class="new-box"><span class="before"></span><span class="after"></span><span class="new">Encerrada</span></div>
      <% end %>
      <div class="product_image"><a href="<%= painel_controle_administrar_oferta_path(product_ad) %>" title="<%= time_ago_in_words(product_ad.end_use_at) %> para finalizar" class="product_image"><img src="<%= product_ad.image.url(:box) %>" alt="<%= time_ago_in_words(product_ad.end_at) %> para finalizar" /></a></div>
      <div class="product_content text-center">
        <% unless product_ad.expired? %>
        <h5 class="countdown text-center alert alert-warning" data-end-at="<%= product_ad.end_at.to_s(:db) %>"></h5>
        <% end -%>
        <h3><%= product_ad.title %></h3>
        <div class="btn-group btn-group-xs">
          <a class="btn btn-default" href="<%=painel_controle_administrar_oferta_path(product_ad) %>" title="administrar"><span>administrar</span></a>
          <a class="btn btn-default" href="<%=painel_controle_administrar_oferta_path(product_ad) %>" title="<%= product_ad.total_coupons %> cupons"><span><%= product_ad.total_coupons %> cupons</span></a>
          <a class="btn btn-default" href="<%=painel_controle_administrar_oferta_path(product_ad) %>" title="<%= product_ad.product_ad_orders.aprovado.count %> vendas"><span><%= product_ad.product_ad_orders.aprovado.count %> vendas</span></a>
        </div>
      </div>
    </div>
  </li>
  <% end %>
</ul>
<% end -%>

app/views/painel_controle/administrar_oferta.html.erb
<div class="breadcrumb">
  <div class="breadcrumb_inset">
    <a class="breadcrumb-home" href="/" title="Retornar a página inicial"><i class="icon-home"></i></a>
    <span class="navigation-pipe">»</span>
    <span class="navigation_page"><a href="<%=minha_conta_path%>">Minha conta</a></span>
    <span class="navigation-pipe">»</span>
    <span class="navigation_page"><a href="<%=painel_controle_path%>">Painel de Controle</a></span>
    <span class="navigation-pipe">»</span>
    <span class="navigation_page">Administração de Oferta</span>
  </div>
</div>

<h1><span>Administração da Oferta: <u><%= @product_ad.title %></u></span></h1>
<div class="row">
  <div class="col-sm-4">
    <img src="<%= @product_ad.image.url %>" />
  </div>
  <div class="col-sm-8">
    <h4>Interesse pela Oferta: <u><strong><%= @product_ad.views %> interesse(s)</strong></u></h4>
    <h4>Vendas concretizadas: <u><strong><%= @product_ad.product_ad_orders.aprovado.count %></strong></u></h4>
    <% if @product_ad.oferta? %>
      <h4>Cupons pendentes de pagamento: <u><strong><%= @product_ad.product_ad_orders.pending.count %></strong></u></h4>
      <h4>Valor a receber: <u><strong><%= number_to_currency @product_ad.product_ad_orders.aprovado.sum(:transfer_price) %></strong></u></h4>
    <% end -%>
  </div>
</div>
<br />
<% unless @product_ad.product_ad_orders.aprovado.nao_utilizado.blank? %>
<div class="well">
  <div class="row">
    <div class='std col-xs-12 col-sm-12'>
      <fieldset class="titled_box">
        <h2><span>Cupons aprovados porém <u>não utilizados</u></span></h2>
        <div class="form_content clearfix">
          <table class="table table-striped table-condensed" id="admCoupons">
            <thead>
            <tr>
              <th>Cupom</th>
              <th>Adquirido por</th>
              <th>CPF/RG</th>
              <th class="col-md-3">Vencimento do Uso</th>
              <th width="230">Ações</th>
            </tr>
            </thead>
            <tbody>
              <% @product_ad.product_ad_orders.aprovado.nao_utilizado.each do |product_ad_order| %>
              <tr>
                <td><h4><%= product_ad_order.coupon %></h4></td>
                <td><h4><%= product_ad_order.client.name %></h4></td>
                <td><h4><%= [product_ad_order.client.cpf, product_ad_order.client.rg].reject{|t| t.blank?}.join(' / ') %></h4></td>
                <td><h4><%= l product_ad_order.end_use_at %></h4></td>
                <td>
                <div class="btn-group btn-group-xs">
                  <%= link_to "Marcar como Utilizado", painel_controle_utilizar_cupon_path(product_ad_order.coupon), class: "btn btn-default btn-primary" %>
                  <%= link_to "Regulamento", "javascript:;", data: {toggle: :modal, target: "#coupon-info#{product_ad_order.coupon}"}, class: "btn btn-default btn-primary" %>
                </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </fieldset>
    </div>
  </div>
</div>
<% @product_ad.product_ad_orders.aprovado.nao_utilizado.each do |product_ad_order| %>
<div class="modal fade" id="coupon-info<%=product_ad_order.coupon%>" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Regulamento adquirido por <strong><%=product_ad_order.order.client.name%></strong> - <%= product_ad_order.coupon %></h4>
      </div>
      <div class="modal-body">
        <%= product_ad_order.terms.to_s.html_safe %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
<% end %>
<% end -%>


<% unless @product_ad.product_ad_orders.aprovado.utilizado.blank? %>
<div class="well">
  <div class="row">
    <div class='std col-xs-12 col-sm-12'>
      <fieldset class="titled_box">
        <h2><span>Cupons aprovadose <u>utilizados</u></span></h2>
        <div class="form_content clearfix">
          <table class="table table-striped table-condensed" id="admCoupons">
            <thead>
            <tr>
              <th>Cupom</th>
              <th>Adquirido por</th>
              <th>CPF/RG</th>
              <th class="col-md-3">Vencimento do Uso</th>
              <th class="col-md-3">Cupom utilizado em</th>
            </tr>
            </thead>
            <tbody>
            <% @product_ad.product_ad_orders.aprovado.utilizado.each do |product_ad_order| %>
              <tr>
                <td><h4><%= product_ad_order.coupon %></h4></td>
                <td><h4><%= product_ad_order.client.name %></h4></td>
                <td><h4><%= [product_ad_order.client.cpf, product_ad_order.client.rg].reject{|t| t.blank?}.join(' / ') %></h4></td>
                <td><h4><%= l product_ad_order.end_use_at %></h4></td>
                <td><h4><%= l product_ad_order.used_at %></h4></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </fieldset>
    </div>
  </div>
</div>
<% end -%>


<% unless @product_ad.product_ad_orders.pending.blank? %>
<div class="well">
  <div class="row">
    <div class='std col-xs-12 col-sm-12'>
      <fieldset class="titled_box">
        <h2><span>Cupons Pendentes de Pagamento</span></h2>
        <div class="form_content clearfix">
          <table class="table table-striped table-condensed" id="admCoupons">
            <thead>
            <tr>
              <th>Adquirido por</th>
              <th>Forma de pagamento</th>
              <th class="col-md-3">Vencimento do Uso</th>
              <th class="col-md-3">Data da Compra</th>
            </tr>
            </thead>
            <tbody>
              <% @product_ad.product_ad_orders.pending.each do |product_ad_order| %>
              <tr>
                <td><h4><%= product_ad_order.client.name %></h4></td>
                <td><h4><%= product_ad_order.order.order_transaction.payment_method.titleize if product_ad_order.order.order_transaction %></h4></td>
                <td><h4><%= l product_ad_order.end_use_at %></h4></td>
                <td><h4><%= l product_ad_order.created_at %></h4></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </fieldset>
    </div>
  </div>
</div>
<% end -%>

app/views/painel_controle/index.html.erb
<div class="breadcrumb">
  <div class="breadcrumb_inset">
    <a class="breadcrumb-home" href="/" title="Retornar a página inicial"><i class="icon-home"></i></a>
    <span class="navigation-pipe">»</span> 
    <span class="navigation_page"><a href="<%=minha_conta_path%>">Minha conta</a></span>
    <span class="navigation-pipe">»</span> 
    <span class="navigation_page">Painel de Controle</span>
  </div>
</div>

<div id="featured-products_block_center" class="main_page_products block">
  <h4><span>Ofertas Ativas</span></h4>
  <%= render partial: 'product_ad_box', locals: {product_ads: @active_product_ads} %>
</div>

<div id="featured-products_block_center" class="main_page_products block">
  <h4><span>Ofertas Encerradas</span></h4>
  <%= render partial: 'product_ad_box', locals: {product_ads: @expired_product_ads} %>
</div>