config/routes.rb
Rails.application.routes.draw do
  resources :company_categories
  resources :admin_clients

  resources :order_transactions do
    collection do
      get :lost
    end
  end

  resources :product_ad_orders

  resources :orders do
    collection do
      get :update_pending, :approved, :pending, :cancelled
    end
    member do
      get 'approve'
      get 'cancel'
      get 'use_all'
      get 'dont_use_all'
      get 'use_coupon'
      get 'dont_use_coupon'
      get 'approve_coupon'
      get 'cancel_coupon'
    end
  end

  resources :product_ad_images

  resources :product_ads do
    member do
      get :duplicate
    end
  end

  resources :site_terms

  resources :pages

  resources :companies do
    collection do
      get :inactives
    end
  end

  resources :advertisements

  resources :cities

  resources :banners

  resources :holidays

  devise_for :clients, path: 'usuarios', path_names: { sign_in: 'entrar', sign_out: 'sair', registration: 'registro', sign_up: 'criar-conta', edit: 'meus-dados', password: 'senha' }
  devise_for :admins

  root 'pagina_inicial#index'

  get 'guia-empresarial' => 'guia_empresarial#index', as: :guia_empresarial
  get 'empresa/:id' => 'guia_empresarial#empresa', as: :empresa
  get 'area-atuacao/empresas/:id' => 'guia_empresarial#empresas_por_area_atuacao', as: :empresas_por_area_atuacao
  get 'ofertas/detalhes/:id' => 'ofertas#detalhes', as: :ofertas_detalhes
  get 'ofertas-disponiveis' => 'ofertas#disponiveis', as: :ofertas_disponiveis
  get 'ofertas-encerradas' => 'ofertas#encerradas', as: :ofertas_encerradas
  get 'minha-conta' => 'minha_conta#index', as: :minha_conta
  get 'minha-conta/validar-email' => 'minha_conta#validar_email', as: :validar_email
  get 'minha-conta/validar-cpf' => 'minha_conta#validar_cpf', as: :validar_cpf
  post 'minha-conta/notificacoes-compra' => 'minha_conta#notificacoes_compra', as: :notificacoes_compra, via: [:post]
  get 'regras-gerais' => 'paginas#regras_gerais', as: :regras_gerais
  get 'cupons' => 'minha_conta#cupons', as: :cupons
  get 'resultado-busca' => 'busca#index', as: :resultado_busca
  get 'cidades' => 'cidades#index', as: :cidades
  get 'trocar-cidade/:id' => 'cidades#trocar', as: :trocar_cidade
  get 'paginas/:link' => 'paginas#index', as: :pagina

  get 'carrinho' => 'carrinho#index', as: :carrinho
  get 'carrinho/adicionar/:id' => 'carrinho#adicionar', as: :carrinho_adicionar, via: [:get, :post]
  get 'carrinho/diminuir/:id' => 'carrinho#diminuir', as: :carrinho_diminuir
  get 'carrinho/remover/:id' => 'carrinho#remover', as: :carrinho_remover
  get 'carrinho/pagamento' => 'carrinho#pagamento', as: :carrinho_pagamento
  post 'carrinho/efetuar-pagamento' => 'carrinho#efetuar_pagamento', as: :carrinho_efetuar_pagamento
  get 'carrinho/processando' => 'carrinho#processando', as: :carrinho_processando

  get 'contato' => 'contato#index', as: :contato
  post 'contato/enviar' => 'contato#enviar', as: :contato_enviar_mensagem

  get 'painel-controle' => 'painel_controle#index', as: :painel_controle
  get 'painel-controle/administrar-oferta/:id' => 'painel_controle#administrar_oferta', as: :painel_controle_administrar_oferta
  get 'painel-controle/utilizar-cupon/:id' => 'painel_controle#utilizar_cupon', as: :painel_controle_utilizar_cupon
  get 'painel-controle/cupons-ativos' => 'painel_controle#cupons_ativos', as: :painel_controle_cupons_ativos
end

app/views/shared/_admin.erb
<li class="divider-vertical"></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> Admin <b class="caret"></b></a>

  <ul class="dropdown-menu">
  <!--
    <li class="dropdown-submenu">
      <a href="#">Administrar Pedidos</a>
      <ul class="dropdown-menu">
        <li><a href="<%= orders_path %>">Todos os pedidos</a></li>
        <li><a href="<%= approved_orders_path %>">Pedidos Aprovados</a></li>
        <li><a href="<%= pending_orders_path %>">Pedidos Pendentes</a></li>
        <li><a href="<%= cancelled_orders_path %>">Pedidos Cancelados</a></li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#">Administrar Transações</a>
      <ul class="dropdown-menu">
        <li><a href="<%= order_transactions_path %>">Todas as Transações</a></li>
        <li><a href="<%= lost_order_transactions_path %>">Transações Perdidas</a></li>
      </ul>
    </li>
    <li><a href="<%=product_ads_path%>">Administrar Ofertas</a></li>
    <li><a href="<%=product_ad_images_path%>">Administrar Imagens de Ofertas</a></li>
    <li><a href="<%=admin_clients_path%>">Administrar Clientes</a></li>
    -->
    <li><a href="<%=companies_path%>">Administrar Anunciantes</a></li>
    <li><a href="<%=inactives_companies_path%>">Administrar Anunciantes Inativos</a></li>
    <li><a href="<%=company_categories_path%>">Administrar Categorias de Anunciantes</a></li>
    <li><a href="<%=banners_path%>">Administrar Banners</a></li>
    <li><a href="<%=advertisements_path%>">Administrar Banners Anúncios</a></li>
    <li><a href="<%=pages_path%>">Administrar Páginas Estáticas</a></li>
    <li><a href="<%=cities_path%>">Administrar Cidades</a></li>
    <li><a href="<%=site_terms_path%>">Administrar Regras Gerais</a></li>
    <li><a href="<%=destroy_admin_session_path%>">Sair da administração</a></li>
  </ul>
</li>

app/views/shared/_advertisements.erb
<div id="minic_slider" class="theme-default">
  <div id="slider" class="nivoSlider" style="display:inline-block;">
    <% @master_advertisements.each do |advertisement| %>
      <%=link_to image_tag(advertisement.image.url(:master), class: :slider_image, title: "#htmlcaption_#{advertisement.id}").html_safe,
      banner_url(advertisement) %>
    <% end %>
  </div>
  <% @master_advertisements.each do |advertisement| %>
  <div id="htmlcaption_<%= advertisement.id %>" class="nivo-html-caption">
    <h3></h3>
    <p>
      <h2><%= advertisement.title %></h2>
      <% unless advertisement.is_a?(ProductAd) %>
      <p class="banner_content"><%= strip_tags advertisement.description %></p>
      <% end -%>
    </p>
  </div>
  <% end %>
</div>

<script type="text/javascript">
$(document).on("page:load ready", function(){
  $('#slider').nivoSlider({
    effect: 'boxRandom',
    slices: 15,
    boxCols: 8,
    boxRows: 4,
    animSpeed: 500,
    pauseTime: 7000,
    startSlide: 0,
    directionNav:true,
    controlNav: true,
    controlNavThumbs: false,
    pauseOnHover: true,
    manualAdvance: false,
    prevText: 'Ant',
    nextText: 'Próx',
    randomStart: false,
    afterLoad:function() {
      var hidden = 1
      if (hidden == 0) {
        $('body').find('#slider .nivo-directionNav').hide();
      }
      $("#slider").swipe({
        swipeLeft:function(event, phase, direction, distance){
          $('body').find('#slider a.nivo-nextNav').trigger('click');
        },
        swipeRight:function(event, phase, direction, distance){
          $('body').find('#slider a.nivo-prevNav').trigger('click');
        },
        triggerOnTouchEnd:false,
        threshold:100
      });
    }
  });
});
</script>
<% unless using_mobile? %>
<div id="htmlcontent_top">
  <ul class="htmlcontent-top row">
    <% @smaller_advertisements.each do |advertisement| %>
    <li class="htmlcontent-item col-xs-4 col-md-12">
      <div>
        <a href="<%= banner_url(advertisement) %>" class="item-link">
          <img src="<%= advertisement.image.url(:small) %>" class="item-img" />
          <% unless advertisement.html_description.blank? %>
          <div class="item-html">
            <div class="banner_container1">
              <%= advertisement.html_description.html_safe %>
            </div>
          </div>
          <% end -%>
        </a>
      </div>
    </li>
    <% end %>
  </ul>
</div>
<% end -%>

app/views/shared/_advertisements_mobile.erb
<div id="minic_slider" class="theme-default">   
  <div id="slider_mobile" class="nivoSlider" style="display:inline-block;">
    <% @master_advertisements.each do |advertisement| %>
      <a href="<%= advertisement.url %>"><img src="<%= advertisement.image.url(:master) %>" class="slider_image" title="#htmlcaption_<%= advertisement.id %>" /></a>
    <% end %>
  </div>
  <% @master_advertisements.each do |advertisement| %>
  <div id="htmlcaption_<%= advertisement.id %>" class="nivo-html-caption">
    <h3></h3>
    <p>
      <h2><%= advertisement.title %></h2>
      <% unless advertisement.is_a?(ProductAd) %>
      <p class="banner_content"><%= strip_tags advertisement.description %></p>
      <% end -%>
    </p>
  </div>
  <% end %>
</div>
<br>


<script type="text/javascript">
$(document).on("page:load ready", function(){
  $('#slider_mobile').nivoSlider({
    effect: 'boxRandom', 
    slices: 15, 
    boxCols: 8, 
    boxRows: 4, 
    animSpeed: 500, 
    pauseTime: 7000, 
    startSlide: 0,
    directionNav:true, 
    controlNav: true, 
    controlNavThumbs: false,
    pauseOnHover: true, 
    manualAdvance: false, 
    prevText: 'Ant', 
    nextText: 'Próx', 
    randomStart: false,
    afterLoad:function() {
      var hidden = 1
      if (hidden == 0) {
        $('body').find('#slider .nivo-directionNav').hide();  
      }
      $("#slider").swipe({
        swipeLeft:function(event, phase, direction, distance){
          $('body').find('#slider a.nivo-nextNav').trigger('click');
        },
        swipeRight:function(event, phase, direction, distance){
          $('body').find('#slider a.nivo-prevNav').trigger('click');
        },
        triggerOnTouchEnd:false,
        threshold:100
      });     
    }
  });
});
</script>

app/views/shared/_banner_top.erb
<% unless using_mobile? %>
  <% if banner_at_top %>
    <a class="container" href="<%= banner_at_top.url %>" title="<%= banner_at_top.title %>" id="topBanner" target="_blank"><img alt="<%= banner_at_top.title %>" src="<%= banner_at_top.image.url %>" width="600" height="114" /></a>
  <% else %>
    <a class="container" href="/contato" id="topBanner"><div>Anuncie aqui! Clique aqui e entre em contato conosco</div></a>
  <% end %>
<% end -%>

app/views/shared/_cart.erb
<li class="divider-vertical"></li>
<li>
  <a href="<%= carrinho_path %>" id="lnkCartTop"><span class="badge"><%= cart.total_qty %></span> cupons</a>
</li>

app/views/shared/_change_password.erb
<div class="modal fade" id="changePassword" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Trocar senha - Informe a nova senha</h4>
      </div>
      <%= form_for(current_client, url: client_registration_path, html: { method: :put, id: 'ClientChangePasswordForm' }) do |f| %>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="required form-group">
              <%= f.label :password %>
              <%= f.text_field :password, class: 'form-control', id: 'ChangeClientPassword', type: :password %>
            </div>
          </div>

          <div class="col-xs-12 col-sm-6">
            <div class="required form-group">
              <%= f.label :password_confirmation %>
              <%= f.text_field :password_confirmation, class: 'form-control', id: 'ChangeClientPassword', type: :password %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12">
            <div class="required form-group">
              <%= f.label :current_password %>
              <%= f.text_field :current_password, class: 'form-control', id: 'ChangeClientPassword', type: :password %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-default btn-primary" id="btnChangePassword">Trocar senha</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_cities.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Empresas em <%= current_city.name %> <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <% all_cities.each do |city| %>
      <% if current_city.id == city.id %>
      <li class="active">
        <a href="/guia-empresarial"><%= city.name %></a>
      </li>
      <% else %>
      <li>
        <a href="<%= trocar_cidade_path(city) %>" title="<%= city.name %>">
          <%= city.name %>
        </a>
      </li>
      <% end %>
    <% end %>
  </ul>
</li>

app/views/shared/_login.erb
<ul class="nav navbar-nav">
  <li>
    <div id="login-at-top">
    <%= form_for :client, url: client_session_path, html: {class: 'form-inline'} do |f| %>
      <div class="form-group">
        <%= f.text_field :email, type: :text, class: 'form-control', placeholder: 'Entre com seu email' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: 'Entre com sua senha' %>
      </div>
      <div class="form-group">
        <button class='btn btn-default btn-sm' type="submit">
          Acessar conta
        </button>
      </div>
      <div class="form-group">
        <a href="<%= new_client_registration_path %>">ou cadastre-se</a>
      </div>
    <% end -%>
    </div>
  </li>
</ul>

app/views/shared/_menu_top.erb
<% unless using_mobile? %>
<section class="header-box blockpermanentlinks-header">
  <ul id="header_links">
    <li><a class="header_links_home" href="/">Página Inicial</a></li>
    <li><a class="guia-empresarial" href="<%=guia_empresarial_path%>" title="Guia Empresarial">Guia Empresarial</a></li>
    <li><a class="anuncie-conosco" href="<%=pagina_path('anuncie-conosco')%>" title="Anuncie Conosco">Anuncie Conosco</a></li>
    <li><a class="contato" href="/contato" title="Contato">Contato</a></li>
  </ul>
</section>
<% end -%>

app/views/shared/_my_account.erb
<li class="divider-vertical"></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> <%= current_client.name %> <b class="caret"></b></a>

  <ul class="dropdown-menu">
    <li class="active"><a href="javascript:;"><%= current_client.email %></a></li>
    <li class="divider"></li>
    <li><a href="<%=minha_conta_path%>">Minha conta</a></li>
    <li><a href="<%= cupons_path %>">Meus cupons</a></li>
    <% if company_signed_in? %>
      <li><a href="<%=painel_controle_path %>">Painel de Controle</a></li>
    <% end %>
    <li class="divider"></li>
    <li><a href="<%=destroy_client_session_path%>">Sair da minha conta</a></li>
  </ul>
</li>

app/views/shared/_product_ad_box.erb
<% product_ads.in_groups_of(4,false).each do |grouped| %>
<ul class="row">
  <% grouped.each do |product_ad| %>
  <li class="ajax_block_product col-xs-6 col-sm-6 col-md-3 first_item_of_line first_item_of_tablet_line">
    <div class="inner_content clearfix">
      <% unless defined?(show_city) %>
        <% if product_ad.newer? %>
        <div class="sale-box"><span class="before"></span><span class="after"></span><span class="on_sale title_shop">Novidade!</span></div>
        <% end %>

        <% if product_ad.ending? %>
        <div class="new-box"><span class="before"></span><span class="after"></span><span class="new">Encerrando!</span></div>
        <% end %>

        
      <% else %>
        <div class="sale-box"><span class="before"></span><span class="after"></span><span class="on_sale title_shop"><%= truncate(product_ad.city.name) %></span></div>
      <% end -%>
      <div class="product_image"><a href="<%= ofertas_detalhes_path(product_ad) %>" title="<%= time_ago_in_words(product_ad.end_at) %> para finalizar" class="product_image"><img src="<%= product_ad.image.url(:box) %>" alt="<%= time_ago_in_words(product_ad.end_at) %> para finalizar" /></a></div>
      <div class="product_content">
        <% if product_ad.can_be_sold? %>
        <h5 class="countdown text-center alert alert-warning" data-end-at="<%= product_ad.end_at.to_s(:db) %>"></h5>
        <% end -%>
        <div class="inner_content1">
          <h5><a class="product_link" href="<%= ofertas_detalhes_path(product_ad) %>" title="<%= number_to_percentage(product_ad.discount, precision: 2) %> de desconto"><%= product_ad.title %></a></h5>
          <p class="price_container"><span class="price"><%= product_ad_price(product_ad) %></span></p>
        </div>
        <a class="button btn btn-default view" href="<%= ofertas_detalhes_path(product_ad) %>" title="Ver Oferta"><i class="icon-info-sign"></i></a>
        <% if product_ad.can_be_sold? %>
        <a class="exclusive btn btn-default ajax_add_to_cart_button btn_add_cart" href="<%=carrinho_adicionar_path(product_ad) %>" title="Adicionar Oferta"><span></span></a>
        <% end -%>
      </div>
    </div>
  </li>
  <% end %>
</ul>
<% end %>

app/views/shared/_register_footer.erb
<% if current_page?(root_path) && !client_signed_in? && !show_advertisement %>
<% close_advertisement %>
<nav class="navbar navbar-default navbar-fixed-bottom hidden-xs hidden-sm">
  <div class="container">
    <div class="row">
      <%= form_tag new_client_registration_path, method: :get do %>
      <div class="std col-xs-12 col-sm-12">
        <fieldset class="titled_box">
          <h2>Receba Ofertas Exclusivas <span class="pull-right"><i class="icon-minus-sign"></i> <a href="javascript:;" id="btnCloseNavFooter">Fechar</a></span></h2>
        </fieldset>
      </div>
      <div class="std col-xs-12 col-sm-12">
        <fieldset class="account_creation titled_box">
          <div class="row">
            <div class="col-xs-12 col-sm-4">
              <div class="form-group">
                <%= label_tag :email %>
                <%= text_field_tag :email, '', autocomplete: "off",  class: "form-control" %>
              </div>
            </div>
            <div class="col-xs-12 col-sm-2">
              <div class="required form-group">
                <div class="input select required">
                  <label>&nbsp;</label>
                  <!-- <a href="" class="btn btn-default form-control">Cadastre-se</a> -->
                  <button type="submit" class="form-control btn btn-default">
                    <i class="icon-user"></i> Cadastre-se
                  </button>
                </div>
              </div>
            </div>
          </div>
        </fieldset>
      </div>
      <% end %>
    </div>
  </div>
</nav>
<% end %>

app/views/shared/_search.erb
<section id="search_block_top" class="header-box">
  <%= form_tag resultado_busca_path, id: :searchbox, method: :get do %>
    <p>
      <label for="search_query_top">Buscar</label>
      <input class="search_query" type="text" id="search_query_top" name="q" value="" />
      <a href="javascript:;" id="btnSearch"><i class="icon-search"></i><span>Buscar</span></a>
    </p>
  <% end %>
</section>

app/views/shared/_site_terms.erb
<div class="modal fade" id="clientTerms" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Termos</h4>
      </div>
      <div class="modal-body">
        <%= client_signed_in? ? current_client.site_term.terms.html_safe : SiteTerm.last.terms.html_safe %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>